In [74]:
import tensorflow as tf
import numpy as np
def printl(a):
    print(a)
    print('====================================================')

# 数据类型
## 数值类型
### 标量,单个数字，shape为[]

In [54]:
a = 1.1
aa =tf.constant(a)
printl(type(a))
printl(type(aa))
printl(tf.is_tensor(aa))

<class 'float'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
True


### 向量shape 为[n,]
与标量不同，向量的定义须通过 List 类型传给 tf.constant()。

In [55]:
# 注意shape的区别，类似numpy
x = tf.constant([[1,2.,3.3]])
printl(x)
y = tf.constant([1,2.,3.3])
printl(y)


tf.Tensor([[1.  2.  3.3]], shape=(1, 3), dtype=float32)
tf.Tensor([1.  2.  3.3], shape=(3,), dtype=float32)


### 矩阵  shape为[n,m]
numpy()方法可以返回 Numpy.array 类型的数据，方便导出数据到系统的其他 模块：

In [56]:
x.numpy()

array([[1. , 2. , 3.3]], dtype=float32)

In [57]:
a = tf.constant([[1,2],[3,4]])
printl(a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


### 3维张量（2纬以上）：  
第一维一般理解为"个数"

In [58]:
a = tf.constant([[[1,2],[3,4]],[[1,2],[3,4]],[[5,6],[7,8]]])
printl(a)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(3, 2, 2), dtype=int32)


## 字符串类型

In [59]:
a = tf.constant('Hello, Deep Learning.')
print(a)

tf.Tensor(b'Hello, Deep Learning.', shape=(), dtype=string)


在 tf.strings 模块中，提供了常见的字符串型的工具函数，如拼接 join()，长度 length()，切 分 split()等等：

In [60]:
b =tf.strings.lower(a)
print(b)

tf.Tensor(b'hello, deep learning.', shape=(), dtype=string)


## boolean 类型


In [61]:
a = tf.constant(True)
print(a)

tf.Tensor(True, shape=(), dtype=bool)


TensorFlow 的布尔类型和 Python 语言的布尔类型对等，能通用：

In [62]:
a = tf.constant(True)
if a:
    print('done')

done


# 数值精度
对于数值类型的张量，可以保持为不同字节长度的精度，如浮点数 3.14 既可以保存为 16-bit 长度，也可以保存为 32-bit 甚至 64-bit 的精度。Bit 位越长，精度越高，同时占用的 内存空间也就越大。常用的精度类型有 tf.int16, tf.int32, tf.int64, tf.float16, tf.float32, tf.float64，其中 tf.float64 即为 tf.double。  
不指定的话，**默认 `tf.float32` 和 `tf.int32`**  
对于大部分深度学习算法，一般使用 tf.int32, tf.float32 可满足运算精度要求，部分对 精度要求较高的算法，如**_强化学习_**，可以选择使用 `tf.int64`, `tf.float64` 精度保存张量。

In [113]:
a = tf.constant(1,dtype = tf.int16)
printl(a)
b =tf.constant(1.2)
printl(b)
c =tf.constant(1)
printl(c)

tf.Tensor(1, shape=(), dtype=int16)
tf.Tensor(1.2, shape=(), dtype=float32)
tf.Tensor(1, shape=(), dtype=int32)


## 精度转换
使用`tf.cast(data，type)`  

In [64]:
a = tf.constant(2 ,dtype = tf.int16)
a = tf.cast(a,tf.float32)
print(a)

tf.Tensor(2.0, shape=(), dtype=float32)


进行类型转换时，需要保证转换操作的合法性，例如将高精度的张量转换为低精度的张量时，可能发生数据**溢出隐患**：

In [65]:
a = tf.constant(123456789, dtype=tf.int32)

print(tf.cast(a, tf.int16))

tf.Tensor(-13035, shape=(), dtype=int16)


布尔型与整形之间相互转换  
整数转bool，只要不是0，都算True

In [66]:
a = tf.constant([True, False])
printl(tf.cast(a, tf.int16))
b = tf.constant([1, 2, 0, 4])
printl(tf.cast(b, tf.bool))


tf.Tensor([1 0], shape=(2,), dtype=int16)
tf.Tensor([ True  True False  True], shape=(4,), dtype=bool)


# 待优化张量
为了区分需要计算梯度信息的张量与不需要计算梯度信息的张量，TensorFlow 增加了 一种专门的数据类型来支持梯度信息的记录：`tf.Variable`。`tf.Variable` 类型在普通的张量类 型基础上添加了 `name`，`trainable` 等属性来支持计算图的构建。由于梯度运算会消耗大量的 计算资源，而且会自动更新相关参数，对于不需要的优化的张量，如神经网络的输入 `X`， 不需要通过 `tf.Variable` 封装；相反，对于需要计算梯度并优化的张量，如神经网络层的`W` 和`𝒃`，需要通过 `tf.Variable` 包裹以便 TensorFlow 跟踪相关梯度信息。

In [67]:
a = tf.constant([-1, 0, 1, 2])

aa = tf.Variable(a)

aa.name, aa.trainable

('Variable:0', True)

name 属性用于命名计算图中的变量，这套命名体系是 TensorFlow 内部维护的，一般**不需要用户关注 name 属性**；trainable 表征当前张量是否需要被优化，创建 Variable 对象是默认启用优化标志，可以设置 `trainable=False` 来设置张量不需要优化。

In [71]:
# 直接创建优化tensor，即 trainable的tensor
b = tf.Variable([2,3,4.])
b

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>

待优化张量可看做普通张量的特殊类型，普通张量也可以通过 `GradientTape.watch()`方法**<font color=red>临时</font>**加入跟踪梯度信息的列表。

# 创建张量
## 从 Numpy, List 对象创建
通过 `tf.convert_to_tensor()` 可以创建新 Tensor，并将保存在 Python List 对象或者 Numpy Array 对象中的数据导入到新 Tensor 中：
需要注意的是，Numpy中浮点数数组默认使用 **64-Bit** 精度保存数据，转换到 Tensor 类型时精度为 **tf.float64**，可以在需要的时候转换为 tf.float32 类型。

In [72]:
tf.convert_to_tensor([1,2.])

<tf.Tensor: id=133, shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [75]:
tf.convert_to_tensor(np.array([[1,2.],[3,4]]))

<tf.Tensor: id=134, shape=(2, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.]])>

## 创建全 0，全 1 张量
通过 `tf.zeros()`和 `tf.ones()`即可创建任意形 状全 0 或全 1 的张量

In [82]:
a = tf.zeros((3,4))
a

<tf.Tensor: id=155, shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [83]:
b = tf.ones((3,4))
b

<tf.Tensor: id=158, shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

通过 `tf.zeros_like()`, `tf.ones_like()` 可以方便地新建与某个张量 shape 一致，内容全 0 或全 1 的张量。

In [85]:
a = tf.constant([[1,2,3],[3,4,5]])
b =tf.ones_like(a)
b

<tf.Tensor: id=166, shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

## 创建自定义数值张量
`tf.fill(shape, value)` shape必须是个一个向量，不能是矩阵，或者已有的tensor

In [103]:
a = tf.fill((3,4),99)
a

<tf.Tensor: id=189, shape=(3, 4), dtype=int32, numpy=
array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99]], dtype=int32)>

## 创建已知分布的张量
通过 `tf.random.normal(shape, mean=0.0, stddev=1.0)`可以创建形状为 shape，均值为 mean，标准差为 stddev 的正态分布𝒩(𝑚𝑒𝑎𝑛, 𝑠𝑡𝑑𝑑𝑒𝑣 2 )。默认 $mean= 0$ and $stddev = 1$

In [105]:
tf.random.normal([1,4])

<tf.Tensor: id=201, shape=(1, 4), dtype=float32, numpy=
array([[-0.8434031 , -1.3420401 ,  0.44487366, -0.4197785 ]],
      dtype=float32)>

In [106]:
tf.random.normal([1,4],20,10)

<tf.Tensor: id=207, shape=(1, 4), dtype=float32, numpy=array([[26.382725 , 19.394056 ,  2.7527008, 16.244581 ]], dtype=float32)>

通过 `tf.random.uniform(shape, minval=0, maxval=None, dtype=tf.float32)`可以创建采样自 [𝑚𝑖𝑛𝑣𝑎𝑙, 𝑚𝑎𝑥𝑣𝑎𝑙]区间的均匀分布的张量。默认$minval = 0$ and $maxval = 1$  
如果需要均匀采样整形类型的数据，必须指定采样区间的最大值 maxval 参数，同时制定数 据类型为 `tf.int*`型：

In [115]:
tf.random.uniform([3,4],5,20,dtype = tf.int32)

<tf.Tensor: id=221, shape=(3, 4), dtype=int32, numpy=
array([[13, 15, 19, 18],
       [18, 18, 13,  6],
       [ 9, 16,  9, 12]], dtype=int32)>

## 创建序列
`tf.range()函数实现。tf.range(limit, delta=1)`可以创建[0, 𝑙𝑖𝑚𝑖𝑡)之间，步长为 delta 的整形序 列，不包含 limit 本身


In [116]:
tf.range(20)

<tf.Tensor: id=225, shape=(20,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int32)>

In [124]:
tf.range(21,delta=3)

<tf.Tensor: id=262, shape=(7,), dtype=int32, numpy=array([ 0,  3,  6,  9, 12, 15, 18], dtype=int32)>

In [125]:
tf.range(10,21,delta=3)

<tf.Tensor: id=266, shape=(4,), dtype=int32, numpy=array([10, 13, 16, 19], dtype=int32)>

# 张量的典型应用