In [2]:
import tensorflow as tf

# Fully-connected Layer

In [7]:
x = tf.random.normal([4,28*28])
fc = tf.keras.layers.Dense(512, activation=tf.nn.relu)
fc(x)

<tf.Tensor: id=72, shape=(4, 512), dtype=float32, numpy=
array([[0.52254856, 0.        , 0.2781079 , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.48528525, 0.        , ..., 1.171781  , 0.16697171,
        0.23927933],
       [0.2988763 , 0.        , 0.        , ..., 0.55242944, 0.        ,
        0.        ],
       [0.        , 0.347023  , 0.        , ..., 0.02008149, 2.2759056 ,
        0.78770864]], dtype=float32)>

In [8]:
fc.kernel # 获取 Dense 类的权值矩阵

<tf.Variable 'dense_1/kernel:0' shape=(784, 512) dtype=float32, numpy=
array([[-0.05976689,  0.0628503 ,  0.01192524, ..., -0.00826678,
        -0.02519222,  0.03400856],
       [ 0.06397717,  0.02950409, -0.04262062, ..., -0.02019756,
        -0.0263237 , -0.05370135],
       [-0.0641872 ,  0.02425408,  0.0356432 , ...,  0.06730963,
        -0.03982457, -0.00586646],
       ...,
       [-0.01039316,  0.05853894,  0.03045898, ..., -0.00365432,
         0.05623828, -0.03076424],
       [-0.00486711,  0.06407167,  0.0139778 , ..., -0.02690298,
         0.00863191, -0.02249521],
       [ 0.01561944,  0.05178192, -0.04530764, ...,  0.01313741,
        -0.02874487, -0.06260533]], dtype=float32)>

In [9]:
fc.bias # 获取 Dense 类的偏置向量

<tf.Variable 'dense_1/bias:0' shape=(512,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 

In [10]:
fc.trainable_variables

[<tf.Variable 'dense_1/kernel:0' shape=(784, 512) dtype=float32, numpy=
 array([[-0.05976689,  0.0628503 ,  0.01192524, ..., -0.00826678,
         -0.02519222,  0.03400856],
        [ 0.06397717,  0.02950409, -0.04262062, ..., -0.02019756,
         -0.0263237 , -0.05370135],
        [-0.0641872 ,  0.02425408,  0.0356432 , ...,  0.06730963,
         -0.03982457, -0.00586646],
        ...,
        [-0.01039316,  0.05853894,  0.03045898, ..., -0.00365432,
          0.05623828, -0.03076424],
        [-0.00486711,  0.06407167,  0.0139778 , ..., -0.02690298,
          0.00863191, -0.02249521],
        [ 0.01561944,  0.05178192, -0.04530764, ...,  0.01313741,
         -0.02874487, -0.06260533]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(512,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

对于全连接层，内部张量都参与梯度优化，故 variables 返回列表与 trainable_variables 一 样。

In [11]:
fc.variables # 返回所有参数列表

[<tf.Variable 'dense_1/kernel:0' shape=(784, 512) dtype=float32, numpy=
 array([[-0.05976689,  0.0628503 ,  0.01192524, ..., -0.00826678,
         -0.02519222,  0.03400856],
        [ 0.06397717,  0.02950409, -0.04262062, ..., -0.02019756,
         -0.0263237 , -0.05370135],
        [-0.0641872 ,  0.02425408,  0.0356432 , ...,  0.06730963,
         -0.03982457, -0.00586646],
        ...,
        [-0.01039316,  0.05853894,  0.03045898, ..., -0.00365432,
          0.05623828, -0.03076424],
        [-0.00486711,  0.06407167,  0.0139778 , ..., -0.02690298,
          0.00863191, -0.02249521],
        [ 0.01561944,  0.05178192, -0.04530764, ...,  0.01313741,
         -0.02874487, -0.06260533]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(512,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

# Activation function
## Softmax 函数
在 Softmax 函数的数值计算过程中，容易因输入值偏大发生数值溢出现象；在计算交叉熵时，也会出现数值溢出的问题。为了数值计算的稳定性，TensorFlow 中提供了一个统一的接口，将 Softmax 与交叉熵损失函数同时实现，同时也处理了数值不稳定的异常，一般推荐使用，避免单独使用 Softmax 函数与交叉熵损失函数。  
### ` tf.keras.losses.categorical_crossentropy(y_true, y_pred, from_logits=False)`  
y_true 代表了 one-hot 编码后的真实标签，y_pred 表示网络的预测值，当 from_logits 设置为 **True** 时， y_pred 表示须为**未经过**Softmax 函数的变量 z；当 from_logits 设置为 **False** 时，y_pred 表示为**经过**Softmax 函数的输出。

In [15]:
z = tf.random.normal([2,10]) # 构造输出层的输出
y_onehot = tf.constant([1,3]) # 构造真实值
y_onehot = tf.one_hot(y_onehot, depth=10) # one-hot 编码
# 输出层未使用 Softmax 函数，故 from_logits 设置为 True
loss = tf.keras.losses.categorical_crossentropy(y_onehot,z,from_logits=True)
loss = tf.reduce_mean(loss) # 计算平均交叉熵损失
loss

<tf.Tensor: id=231, shape=(), dtype=float32, numpy=2.531877>

### `tf.keras.losses.CategoricalCrossentropy(from_logits)`
新建这个类的实例，实现 Softmax 与交叉熵损失函数的计算：

In [16]:
# 创建 Softmax 与交叉熵计算类，输出层的输出 z 未使用 softmax
criteon = tf.keras.losses.CategoricalCrossentropy(from_logits=True)
loss = criteon(y_onehot,z) # 计算损失
loss

<tf.Tensor: id=281, shape=(), dtype=float32, numpy=2.531877>

# Loss function
## MSE

In [3]:
o = tf.random.normal([2,10]) # 构造网络输出
y_onehot = tf.constant([1,3]) # 构造真实值
y_onehot = tf.one_hot(y_onehot, depth=10)
loss = tf.keras.losses.MSE(y_onehot, o) # 计算均方差
loss

<tf.Tensor: id=13, shape=(2,), dtype=float32, numpy=array([0.54997844, 0.9532288 ], dtype=float32)>

TensorFlow MSE 函数返回的是每个样本的均方差，需要在样本数量上再次平均来获得 batch 的均方差：

In [24]:
loss = tf.reduce_mean(loss) # 计算 batch 均方差
loss

<tf.Tensor: id=369, shape=(), dtype=float32, numpy=0.7481604>

也可以通过类方式实现，对应的类为 keras.losses.MeanSquaredError()：

In [26]:
# 创建 MSE 类
criteon = tf.keras.losses.MeanSquaredError()
loss = criteon(y_onehot,o) # 计算 batch 均方差
loss

<tf.Tensor: id=409, shape=(), dtype=float32, numpy=0.7481604>